### ISSUE TITLE
df_2009zensho_sの前処理

### ISSUE THREAD

**Issue by taku-y** [hannari-python/tutorial#11]
統計センター 一般用ミクロデータの三種類のデータのうち、**df_2009zensho_s** を使う。
* [x] 項目情報を確認するための pandas.read_excel の使い方のcellの追加
  * ippan_2009zensho_s.xlsにデータの説明がある
* [x] `ippan_2009zensho_s/ippan_2009zensho_s_dataset.csv` の各列に何個欠損値があるかを調べる

**Comment by kozo2** [comment]
`ippan_2009zensho_s/ippan_2009zensho_s_dataset.csv`
の各列の値なんですが
一つも欠損値が無さそうでした。
(See https://github.com/hannari-python/tutorial/blob/master/household/visualizing_df_2009zensho_s.ipynb)
