### ISSUE TITLE
[貿易収支] ノートブックの統合

### ISSUE THREAD

**Issue by taku-y** [hannari-python/tutorial#27]

**Comment by mazarimono** [comment]
@taku-y 解説の時間配分ですが、60分ずつくらいの持ち時間でよろしいでしょうか？

**Comment by mazarimono** [comment]
@taku-y ノートブックですが、次のノートで1冊にまとめるよう更新したのですが、吉岡さんの部分でエラーが出るようになってしまいました。すみません。お時間ある時に確認いただけますと幸いです。
https://github.com/hannari-python/tutorial/blob/master/trade_balance/trade_balance_prepro_and_visualization_and_clustering.ipynb

**Comment by taku-y** [comment]
@mazarimono 貿易データのノートブックを更新し、先ほど通して再実行してエラーが出ないことを確認しました。もしお時間があれば小川さんの方でも動作確認頂ければと思います。一旦このissueはcloseします。
