### ISSUE TITLE
このリポジトリへのライセンスの設定

### ISSUE THREAD

**Issue by kozo2** [hannari-python/tutorial#32]
貿易収支のデータセットのライセンスが
CC BY-SA 4.0
であることに合わせてこのリポジトリのライセンスも
CC BY-SA 4.0
にするのはどうかと。
気になるのは 地理情報のコースで扱うデータです。
そこがクリアされてればCC BY-SA 4.0に設定できるかと思います。

**Comment by ksnt** [comment]
スクレイピングしてきたデータを使わないことにして、国土数値情報のデータから同じものを作り直しました。

このデータは「本利用ルールは、クリエイティブ・コモンズ・ライセンスの表示4.0国際（https://creativecommons.org/licenses/by/4.0/legalcode.jaに規定される著作権利用許諾条件。以下「CCBY」といいます。）と互換性があり、本利用ルールが適用されるコンテンツはCCBYに従うことでも利用することができます。」とのことです。

これで、CC BY-SA 4.0が使えるのではないかと思われます。利用ルール(利用規定)の詳細は、[こちら](https://nlftp.mlit.go.jp/ksj/other/agreement.html#agree-02)に書かれています。

**Comment by kozo2** [comment]
READMEを更新してライセンスについて言及しました。
「まあこんな感じでいいんじゃないかな」という感じになってるかと。
