### ISSUE TITLE
チェックポイント（小川, 西田）

### ISSUE THREAD

**Issue by mazarimono** [hannari-python/tutorial#36]
- [x] 質問の回答を作成する
- [x] mapの解説
- [ ] try except 
- [x] 西田さんとのplotly / dashの解説のかぶらないように確認

**Comment by kozo2** [comment]
#34 をここに移します
- [x] **分析の目的** をデータを見た後に意思共有する(ようなmarkdownセルを書く)
- [x] そのセルが何をしようとしているものかを簡潔に述べる
- [x] 図の横縦軸の説明を行う
- [x] テーブルの行と列の説明
- [x] データの出典と利用許諾情報
